name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch configuration
        uses: gbraad-actions/shared-config@v2
        with:
          config_repo: https://github.com/gbraad/shared-config.git
          config_file: ${{ github.repository }}/test.ini

      - name: Use test settings
        run: |
          echo "Author: $TEST_NAME $TEST_EMAIL"
        shell: bash

      - name: Use quoted settings
        run: |
          echo "Author: ${{ env.QUOTED_NAME }} ${{ env.QUOTED_EMAIL }}"
        shell: bash

      - name: Fetch configuration and use output
        id: shared-config
        uses: gbraad-actions/shared-config@v2
        with:
          config_repo: https://github.com/gbraad/shared-config.git
          config_file: ${{ github.repository }}/test-output.ini
          use_output: true

      - name: Use test and test-output settings
        run: |
          echo "Contact: $TEST_EMAIL or ${{ steps.shared-config.outputs.TEST_EMAIL }}"
        shell: bash
